#!/usr/bin/env python3
"""
Live Dot Plot Viewer for CPFA Visited Positions Data
Monitors CSV files generated by the C++ simulation and displays live dot plots
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from matplotlib.patches import Rectangle
import glob
import os
import time
import argparse

class LiveDotplotViewer:
    def __init__(self, csv_pattern="dotplot_data/visited_positions_*.csv", update_interval=2000):
        self.csv_pattern = csv_pattern
        self.update_interval = update_interval  # milliseconds
        self.fig, self.ax = plt.subplots(figsize=(12, 10))
        self.last_file = None
        self.positions_data = None
        
        # Setup the plot
        self.ax.set_title('Robot Visited Positions - Live View', fontsize=16)
        self.ax.set_xlabel('X Position (meters)', fontsize=12)
        self.ax.set_ylabel('Y Position (meters)', fontsize=12)
        self.ax.grid(True, alpha=0.3)
        self.ax.set_aspect('equal')
        
    def find_latest_csv(self):
        """Find the most recent CSV file matching the pattern"""
        files = glob.glob(self.csv_pattern)
        if not files:
            return None
        
        # Sort by modification time, get the latest
        latest_file = max(files, key=os.path.getmtime)
        return latest_file
    
    def load_positions_data(self, filename):
        """Load position data from CSV file"""
        try:
            # Read the CSV file, skipping header comments
            df = pd.read_csv(filename, comment='#')
            
            # Extract X,Y coordinates
            positions_x = df['X'].values
            positions_y = df['Y'].values
            
            # Extract metadata and cluster information from comments
            metadata = {}
            clusters = []
            
            with open(filename, 'r') as f:
                for line in f:
                    if line.startswith('#'):
                        if 'Simulation Time:' in line:
                            metadata['sim_time'] = line.split(':')[1].strip().split()[0]
                        elif 'Total Positions:' in line:
                            metadata['total_positions'] = line.split(':')[1].strip()
                        elif 'Food Distribution:' in line:
                            metadata['food_distribution'] = line.split(':')[1].strip()
                        elif 'Number of Clusters:' in line:
                            metadata['num_clusters'] = int(line.split(':')[1].strip())
                        elif 'Cluster Dimensions:' in line:
                            metadata['cluster_dimensions'] = line.split(':')[1].strip()
                        elif 'Food Radius:' in line:
                            metadata['food_radius'] = float(line.split(':')[1].strip())
                        elif 'Cluster ' in line and ':' in line and line.strip().startswith('# Cluster '):
                            # Parse cluster center: "# Cluster 0: -1.5,2.3"
                            parts = line.split(':')
                            if len(parts) >= 2:  # Make sure we have enough parts
                                cluster_info = parts[1].strip()  # Get the coordinates part (it's the second part)
                                coords = cluster_info.split(',')
                                if len(coords) == 2:
                                    try:
                                        x, y = float(coords[0]), float(coords[1])
                                        clusters.append((x, y))
                                    except ValueError:
                                        pass
                    else:
                        break
            
            metadata['clusters'] = clusters
            return positions_x, positions_y, metadata
            
        except Exception as e:
            print(f"Error loading {filename}: {e}")
            return None, None, {}
    
    def draw_cluster_backgrounds(self, metadata):
        """Draw cluster backgrounds as shaded rectangles"""
        clusters = metadata.get('clusters', [])
        if not clusters:
            return
        
        # Get cluster parameters
        cluster_dims = metadata.get('cluster_dimensions', '8x8')
        try:
            width_str, height_str = cluster_dims.split('x')
            cluster_width = int(width_str)
            cluster_height = int(height_str)
        except:
            cluster_width = 8  # default
            cluster_height = 8  # default
            
        food_radius = metadata.get('food_radius', 0.05)
        food_offset = 3.0 * food_radius  # This matches the C++ code
        
        # Calculate actual cluster dimensions in world coordinates
        actual_width = cluster_width * food_offset
        actual_height = cluster_height * food_offset
        
        # Draw each cluster as a semi-transparent rectangle
        for i, (center_x, center_y) in enumerate(clusters):
            # Create rectangle patch (cluster extends from center to center + dimensions)
            rect = Rectangle((center_x, center_y), actual_width, actual_height,
                           linewidth=2, edgecolor='red', facecolor='red', 
                           alpha=0.2, label='Food Clusters' if i == 0 else "")
            self.ax.add_patch(rect)
            
            # Add cluster center marker
            self.ax.plot(center_x + actual_width/2, center_y + actual_height/2, 
                        'r+', markersize=12, markeredgewidth=2, alpha=0.8)
    
    def update_dotplot(self, frame):
        """Animation function called periodically"""
        latest_file = self.find_latest_csv()
        
        if latest_file is None:
            # No files found yet
            self.ax.clear()
            self.ax.text(0.5, 0.5, 'Waiting for CSV files...', 
                        transform=self.ax.transAxes, ha='center', va='center',
                        fontsize=14, color='red')
            self.ax.set_title('Robot Visited Positions - Live View', fontsize=16)
            return []
        
        # Only update if we have a new file
        if latest_file != self.last_file:
            self.last_file = latest_file
            
            positions_x, positions_y, metadata = self.load_positions_data(latest_file)
            
            if positions_x is not None and positions_y is not None:
                # Clear the axes
                self.ax.clear()
                
                if len(positions_x) > 0:
                    # Draw cluster backgrounds first (if available)
                    self.draw_cluster_backgrounds(metadata)
                    
                    # Create color array based on visit order (temporal progression)
                    colors = np.arange(len(positions_x))
                    
                    # Create the scatter plot with color mapping
                    scatter = self.ax.scatter(positions_x, positions_y, c=colors, 
                                            cmap='viridis', alpha=0.7, s=30, 
                                            edgecolors='black', linewidth=0.5)
                    
                    # Add colorbar if not already present or update it
                    if not hasattr(self, 'cbar'):
                        self.cbar = plt.colorbar(scatter, ax=self.ax)
                        self.cbar.set_label('Visit Order (Earlier→Later)', rotation=270, labelpad=20)
                    else:
                        self.cbar.update_normal(scatter)
                    
                    # Calculate statistics
                    total_positions = len(positions_x)
                    x_range = np.max(positions_x) - np.min(positions_x) if len(positions_x) > 1 else 0
                    y_range = np.max(positions_y) - np.min(positions_y) if len(positions_y) > 1 else 0
                    mean_x = np.mean(positions_x)
                    mean_y = np.mean(positions_y)
                    std_x = np.std(positions_x)
                    std_y = np.std(positions_y)
                    
                    # Update titles and labels
                    sim_time = metadata.get('sim_time', 'Unknown')
                    
                    self.ax.set_title(f'Robot Visited Positions - Live View\n'
                                    f'Time: {sim_time}s | Total Positions: {total_positions}\n',
                                    fontsize=14)
                    
                    # Add mean position marker
                    # self.ax.plot(mean_x, mean_y, 'r+', markersize=15, markeredgewidth=3, 
                    #            label=f'Mean Position ({mean_x:.2f}, {mean_y:.2f})')
                    
                    # Add legend (only if clusters are present)
                    clusters = metadata.get('clusters', [])
                    if clusters:
                        self.ax.legend(loc='upper right')
                    
                    # Add statistics text box
                    # stats_text = f'Statistics:\n'
                    # stats_text += f'Mean X: {mean_x:.2f}m\n'
                    # stats_text += f'Mean Y: {mean_y:.2f}m\n'
                    # stats_text += f'Std X: {std_x:.2f}m\n'
                    # stats_text += f'Std Y: {std_y:.2f}m\n'
                    # stats_text += f'X Range: [{np.min(positions_x):.2f}, {np.max(positions_x):.2f}]\n'
                    # stats_text += f'Y Range: [{np.min(positions_y):.2f}, {np.max(positions_y):.2f}]'
                    
                    # self.ax.text(0.02, 0.98, stats_text, transform=self.ax.transAxes,
                    #            verticalalignment='top', bbox=dict(boxstyle='round', 
                    #            facecolor='wheat', alpha=0.8), fontsize=10)
                    
                    # Set equal aspect ratio and add grid
                    self.ax.set_aspect('equal')
                    self.ax.grid(True, alpha=0.3)
                    
                    # Set axis limits to match arena size (10x10 arena = -5 to +5)
                    arena_half_size = 4
                    self.ax.set_xlim(-arena_half_size, arena_half_size)
                    self.ax.set_ylim(-arena_half_size, arena_half_size)
                    
                    # Add grid lines at 1 meter intervals for 10x10 arena
                    grid_positions = np.arange(-arena_half_size, arena_half_size + 1, 1)
                    self.ax.set_xticks(grid_positions)
                    self.ax.set_yticks(grid_positions)
                    
                else:
                    # No position data yet
                    self.ax.text(0.5, 0.5, 'No position data available yet', 
                                ha='center', va='center', transform=self.ax.transAxes,
                                fontsize=14, color='orange')
                    sim_time = metadata.get('sim_time', 'Unknown')
                    self.ax.set_title(f'Robot Visited Positions - Live View\n'
                                    f'Time: {sim_time}s | Total Positions: 0', 
                                    fontsize=14)
                
                self.ax.set_xlabel('X Position', fontsize=12)
                self.ax.set_ylabel('Y Position', fontsize=12)
                
                print(f"Updated dot plot from {latest_file} (Time: {metadata.get('sim_time', 'Unknown')}s, "
                      f"Positions: {len(positions_x) if positions_x is not None else 0})")
        
        return []
    
    def start_animation(self):
        """Start the live animation"""
        print(f"Starting live dot plot viewer...")
        print(f"Looking for files matching: {self.csv_pattern}")
        print(f"Update interval: {self.update_interval/1000:.1f} seconds")
        print("Close the window to exit.")
        
        # Create animation
        ani = animation.FuncAnimation(self.fig, self.update_dotplot, 
                                    interval=self.update_interval, 
                                    blit=False, cache_frame_data=False)
        
        # Show the plot
        plt.tight_layout()
        plt.show()
        
        return ani

def main():
    parser = argparse.ArgumentParser(description='Live Dot Plot Viewer for CPFA Visited Positions Data')
    parser.add_argument('--pattern', default='dotplot_data/visited_positions_*.csv',
                       help='CSV file pattern to monitor (default: dotplot_data/visited_positions_*.csv)')
    parser.add_argument('--interval', type=int, default=2000,
                       help='Update interval in milliseconds (default: 2000)')
    
    args = parser.parse_args()
    
    try:
        viewer = LiveDotplotViewer(csv_pattern=args.pattern, 
                                 update_interval=args.interval)
        ani = viewer.start_animation()
        
    except KeyboardInterrupt:
        print("\nViewer stopped by user.")
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()