#!/usr/bin/env python3
"""
Live Heatmap Viewer for CPFA Grid Data
Monitors CSV files generated by the C++ simulation and displays live heatmaps
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from matplotlib.colors import LinearSegmentedColormap
import glob
import os
import time
import argparse

class LiveHeatmapViewer:
    def __init__(self, csv_pattern="heatmap_data/grid_heatmap_*.csv", update_interval=2000):
        self.csv_pattern = csv_pattern
        self.update_interval = update_interval  # milliseconds
        self.fig, self.ax = plt.subplots(figsize=(12, 8))
        self.im = None
        self.last_file = None
        self.grid_data = None
        
        # Create custom colormap (white to dark red)
        colors = ['white', 'lightcoral', 'red', 'darkred', 'maroon']
        self.cmap = LinearSegmentedColormap.from_list('visit_count', colors)
        
        # Setup the plot
        self.ax.set_title('Robot Visit Count Heatmap - Live View', fontsize=16)
        self.ax.set_xlabel('Grid X Coordinate', fontsize=12)
        self.ax.set_ylabel('Grid Y Coordinate', fontsize=12)
        
    def find_latest_csv(self):
        """Find the most recent CSV file matching the pattern"""
        files = glob.glob(self.csv_pattern)
        if not files:
            return None
        
        # Sort by modification time, get the latest
        latest_file = max(files, key=os.path.getmtime)
        return latest_file
    
    def load_grid_data(self, filename):
        """Load grid data from CSV file"""
        try:
            # Read the CSV file, skipping header comments
            df = pd.read_csv(filename, comment='#', index_col=0)
            
            # Convert to numpy array for heatmap
            grid_array = df.values.astype(float)
            
            # Extract metadata from comments
            metadata = {}
            with open(filename, 'r') as f:
                for line in f:
                    if line.startswith('#'):
                        if 'Simulation Time:' in line:
                            metadata['sim_time'] = line.split(':')[1].strip().split()[0]
                        elif 'Grid Dimensions:' in line:
                            metadata['dimensions'] = line.split(':')[1].strip()
                        elif 'Cell Size:' in line:
                            metadata['cell_size'] = line.split(':')[1].strip().split()[0]
                    else:
                        break
            
            return grid_array, metadata
            
        except Exception as e:
            print(f"Error loading {filename}: {e}")
            return None, {}
    
    def update_heatmap(self, frame):
        """Animation function called periodically"""
        latest_file = self.find_latest_csv()
        
        if latest_file is None:
            # No files found yet
            self.ax.text(0.5, 0.5, 'Waiting for CSV files...', 
                        transform=self.ax.transAxes, ha='center', va='center',
                        fontsize=14, color='red')
            return []
        
        # Only update if we have a new file
        if latest_file != self.last_file:
            self.last_file = latest_file
            
            grid_data, metadata = self.load_grid_data(latest_file)
            
            if grid_data is not None:
                self.grid_data = grid_data
                
                # Clear the axes
                self.ax.clear()
                
                # Get grid dimensions
                height, width = grid_data.shape
                
                # For 8x8 arena: world extends from -4 to +4, grid lines at integers
                # Cell centers are at half-integers: -3.5, -2.5, -1.5, -0.5, 0.5, 1.5, 2.5, 3.5
                arena_half_size = width // 2  # 4 for 8x8 grid
                
                # Create the heatmap with extent from -4 to +4
                self.im = self.ax.imshow(grid_data, cmap=self.cmap, 
                                       interpolation='nearest', origin='lower',
                                       extent=[-arena_half_size, arena_half_size,
                                              -arena_half_size, arena_half_size])
                
                # Add colorbar if not already present
                if not hasattr(self, 'cbar'):
                    self.cbar = plt.colorbar(self.im, ax=self.ax)
                    self.cbar.set_label('Visit Count', rotation=270, labelpad=20)
                else:
                    self.cbar.update_normal(self.im)
                
                # Update titles and labels
                sim_time = metadata.get('sim_time', 'Unknown')
                dimensions = metadata.get('dimensions', 'Unknown')
                cell_size = metadata.get('cell_size', 'Unknown')
                
                self.ax.set_title(f'Robot Visit Count Heatmap\n'
                                f'Time: {sim_time}s | Grid: {dimensions} | Cell: {cell_size}m', 
                                fontsize=14)
                self.ax.set_xlabel('World X Coordinate (meters)', fontsize=12)
                self.ax.set_ylabel('World Y Coordinate (meters)', fontsize=12)
                
                # Grid lines at integer positions: -4, -3, -2, -1, 0, 1, 2, 3, 4
                grid_lines = np.arange(-arena_half_size, arena_half_size + 1, 1)
                
                # Draw grid lines
                # for x in grid_lines:
                #     self.ax.axvline(x, color='gray', alpha=0.3, linewidth=0.5)
                # for y in grid_lines:
                #     self.ax.axhline(y, color='gray', alpha=0.3, linewidth=0.5)
                
                # Set ticks at grid line positions
                self.ax.set_xticks(grid_lines)
                self.ax.set_yticks(grid_lines)
                
                # Add visit count text inside each cell
                for i in range(height):
                    for j in range(width):
                        visit_count = int(grid_data[i, j])
                        # Calculate world coordinates for cell centers
                        # The extent goes from -arena_half_size to +arena_half_size
                        # Cell centers should be at the middle of each cell
                        x_pos = -arena_half_size + (j + 0.5) * (2 * arena_half_size / width)  # Cell center X
                        y_pos = -arena_half_size + (i + 0.5) * (2 * arena_half_size / height)  # Cell center Y
                        
                        # Choose text color based on visit count for better visibility
                        text_color = 'white' if visit_count > np.max(grid_data) * 0.5 else 'black'
                        
                        self.ax.text(x_pos, y_pos, str(visit_count), 
                                   ha='center', va='center', 
                                   fontsize=10, fontweight='bold',
                                   color=text_color)
                
                # Add text annotation with statistics
                max_visits = np.max(grid_data)
                total_visits = np.sum(grid_data)
                visited_cells = np.count_nonzero(grid_data)
                total_cells = grid_data.size
                
                stats_text = f'Max visits: {max_visits:.0f}\n'
                stats_text += f'Total visits: {total_visits:.0f}\n'
                stats_text += f'Visited cells: {visited_cells}/{total_cells}'
                
                self.ax.text(0.02, 0.98, stats_text, transform=self.ax.transAxes,
                           verticalalignment='top', bbox=dict(boxstyle='round', 
                           facecolor='white', alpha=0.8), fontsize=10)
                
                print(f"Updated heatmap from {latest_file} (Time: {sim_time}s)")
        
        return []
    
    def start_animation(self):
        """Start the live animation"""
        print(f"Starting live heatmap viewer...")
        print(f"Looking for files matching: {self.csv_pattern}")
        print(f"Update interval: {self.update_interval/1000:.1f} seconds")
        print("Close the window to exit.")
        
        # Create animation
        ani = animation.FuncAnimation(self.fig, self.update_heatmap, 
                                    interval=self.update_interval, 
                                    blit=False, cache_frame_data=False)
        
        # Show the plot
        plt.tight_layout()
        plt.show()
        
        return ani

def main():
    parser = argparse.ArgumentParser(description='Live Heatmap Viewer for CPFA Grid Data')
    parser.add_argument('--pattern', default='heatmap_data/grid_heatmap_*.csv',
                       help='CSV file pattern to monitor (default: heatmap_data/grid_heatmap_*.csv)')
    parser.add_argument('--interval', type=int, default=2000,
                       help='Update interval in milliseconds (default: 2000)')
    
    args = parser.parse_args()
    
    try:
        viewer = LiveHeatmapViewer(csv_pattern=args.pattern, 
                                 update_interval=args.interval)
        ani = viewer.start_animation()
        
    except KeyboardInterrupt:
        print("\nViewer stopped by user.")
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()