#!/usr/bin/env python3
"""
Live Heatmap and Food Viewer for CPFA Grid Data
Monitors CSV files generated by the C++ simulation and displays live heatmaps with food locations
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from matplotlib.colors import LinearSegmentedColormap
import glob
import os
import time
import argparse

class LiveHeatmapFoodViewer:
    def __init__(self, heatmap_pattern="heatmap_data/grid_heatmap_*.csv", 
                 food_pattern="food_data/food_locations_*.csv",
                 update_interval=2000):
        self.heatmap_pattern = heatmap_pattern
        self.food_pattern = food_pattern
        self.update_interval = update_interval  # milliseconds
        self.fig, self.ax = plt.subplots(figsize=(14, 10))
        self.im = None
        self.last_heatmap_file = None
        self.last_food_file = None
        self.grid_data = None
        self.food_data = None
        
        # Create custom colormap (white to dark red)
        colors = ['white', 'lightcoral', 'red', 'darkred', 'maroon']
        self.cmap = LinearSegmentedColormap.from_list('visit_count', colors)
        
        # Setup the plot
        self.ax.set_title('Robot Visit Count Heatmap with Food Locations - Live View', fontsize=16)
        self.ax.set_xlabel('World X Coordinate (meters)', fontsize=12)
        self.ax.set_ylabel('World Y Coordinate (meters)', fontsize=12)
        
    def find_latest_csv(self, pattern):
        """Find the most recent CSV file matching the pattern"""
        files = glob.glob(pattern)
        if not files:
            return None
        
        # Sort by modification time, get the latest
        latest_file = max(files, key=os.path.getmtime)
        return latest_file
    
    def load_grid_data(self, filename):
        """Load grid data from CSV file"""
        try:
            # Read the CSV file, skipping header comments
            df = pd.read_csv(filename, comment='#', index_col=0)
            
            # Convert to numpy array for heatmap
            grid_array = df.values.astype(float)
            
            # Extract metadata from comments
            metadata = {}
            with open(filename, 'r') as f:
                for line in f:
                    if line.startswith('#'):
                        if 'Simulation Time:' in line:
                            metadata['sim_time'] = line.split(':')[1].strip().split()[0]
                        elif 'Grid Dimensions:' in line:
                            metadata['dimensions'] = line.split(':')[1].strip()
                        elif 'Cell Size:' in line:
                            metadata['cell_size'] = line.split(':')[1].strip().split()[0]
                    else:
                        break
            
            return grid_array, metadata
            
        except Exception as e:
            print(f"Error loading heatmap {filename}: {e}")
            return None, {}
    
    def load_food_data(self, filename):
        """Load food location data from CSV file"""
        try:
            # Read the CSV file, skipping header comments
            df = pd.read_csv(filename, comment='#')
            
            # Extract metadata from comments
            metadata = {}
            with open(filename, 'r') as f:
                for line in f:
                    if line.startswith('#'):
                        if 'Simulation Time:' in line:
                            metadata['sim_time'] = line.split(':')[1].strip().split()[0]
                        elif 'Food Count:' in line:
                            metadata['food_count'] = line.split(':')[1].strip()
                        elif 'Food Distribution:' in line:
                            metadata['distribution'] = line.split(':')[1].strip()
                    else:
                        break
            
            return df, metadata
            
        except Exception as e:
            print(f"Error loading food data {filename}: {e}")
            return None, {}
    
    def update_display(self, frame):
        """Animation function called periodically"""
        latest_heatmap = self.find_latest_csv(self.heatmap_pattern)
        latest_food = self.find_latest_csv(self.food_pattern)
        
        # Check if we have new data
        heatmap_updated = latest_heatmap != self.last_heatmap_file
        food_updated = latest_food != self.last_food_file
        
        if not heatmap_updated and not food_updated:
            # No updates needed
            return []
        
        # Load new data if available
        if heatmap_updated and latest_heatmap is not None:
            self.last_heatmap_file = latest_heatmap
            self.grid_data, self.heatmap_metadata = self.load_grid_data(latest_heatmap)
            
        if food_updated and latest_food is not None:
            self.last_food_file = latest_food
            self.food_data, self.food_metadata = self.load_food_data(latest_food)
        
        # Redraw the display
        self.redraw_display()
        
        return []
    
    def redraw_display(self):
        """Redraw the entire display with current data"""
        # Clear the axes
        self.ax.clear()
        
        # Draw heatmap if available
        if self.grid_data is not None:
            # Get grid dimensions
            height, width = self.grid_data.shape
            
            # Arena extends from -4 to +4 (8x8 arena)
            arena_half_size = 4
            
            # Create the heatmap
            self.im = self.ax.imshow(self.grid_data, cmap=self.cmap, 
                                   interpolation='nearest', origin='lower',
                                   extent=[-arena_half_size, arena_half_size,
                                          -arena_half_size, arena_half_size],
                                   alpha=0.8)  # Make slightly transparent for food visibility
            
            # Add colorbar if not already present
            if not hasattr(self, 'cbar'):
                self.cbar = plt.colorbar(self.im, ax=self.ax)
                self.cbar.set_label('Visit Count', rotation=270, labelpad=20)
            else:
                self.cbar.update_normal(self.im)
            
            # Add visit count text inside each cell
            # Calculate actual cell size from C++ grid system
            arena_width = 2 * arena_half_size  # 8 meters
            nominal_cell_size = 0.75
            num_cells = int(np.ceil(arena_width / nominal_cell_size))  # 11 cells
            actual_cell_size = arena_width / num_cells  # 8/11 ≈ 0.727m
            
            # Adjust font size based on actual cell size
            base_font_size = 8
            font_size = max(8, min(16, int(base_font_size * actual_cell_size / 0.25)))
            
            for i in range(height):
                for j in range(width):
                    visit_count = int(self.grid_data[i, j])
                    if visit_count > 0:  # Only show non-zero counts
                        # Calculate world coordinates for cell centers
                        x_pos = -arena_half_size + (j + 0.5) * (2 * arena_half_size / width)
                        y_pos = -arena_half_size + (i + 0.5) * (2 * arena_half_size / height)
                        
                        # Choose text color based on visit count for better visibility
                        text_color = 'white' if visit_count > np.max(self.grid_data) * 0.5 else 'black'
                        
                        self.ax.text(x_pos, y_pos, str(visit_count), 
                                   ha='center', va='center', 
                                   fontsize=font_size, fontweight='bold',
                                   color=text_color)
        
        # Draw food locations if available
        if self.food_data is not None and not self.food_data.empty:
            # Plot food as yellow circles with black outline
            self.ax.scatter(self.food_data['X'], self.food_data['Y'], 
                          c='yellow', s=100, marker='o', 
                          edgecolors='black', linewidth=2, 
                          label=f'Food ({len(self.food_data)} items)',
                          zorder=10)  # Ensure food is drawn on top
            
            # Add food radius circles if FoodRadius is available
            if hasattr(self, 'food_metadata') and 'food_radius' in self.food_metadata:
                food_radius = float(self.food_metadata['food_radius'])
                for _, row in self.food_data.iterrows():
                    circle = plt.Circle((row['X'], row['Y']), food_radius, 
                                      fill=False, color='orange', 
                                      linewidth=1, alpha=0.7, zorder=9)
                    self.ax.add_patch(circle)
        
        # Draw nest location (always at origin based on XML)
        nest_x, nest_y = 0, 0
        nest_radius = 0.15  # From XML configuration
        nest_circle = plt.Circle((nest_x, nest_y), nest_radius, 
                               color='green', alpha=0.7, 
                               label='Nest', zorder=10)
        self.ax.add_patch(nest_circle)
        
        # Set up the plot appearance
        arena_half_size = 4
        self.ax.set_xlim(-arena_half_size, arena_half_size)
        self.ax.set_ylim(-arena_half_size, arena_half_size)
        
        # Grid lines based on actual C++ grid system
        # From C++: GridWidth = ceil(8.0 / 0.75) = 11 cells
        # Each cell is actually 8/11 ≈ 0.727m wide, not 0.75m
        
        arena_width = 2 * arena_half_size  # 8 meters
        nominal_cell_size = 0.75
        num_cells = int(np.ceil(arena_width / nominal_cell_size))  # 11 cells
        actual_cell_size = arena_width / num_cells  # 8/11 ≈ 0.727m
        
        # Create grid positions that match the C++ grid exactly
        # 11 cells means 12 grid lines (boundaries)
        grid_positions = np.linspace(-arena_half_size, arena_half_size, num_cells + 1)
        
        # Draw grid lines at cell boundaries only
        for x in grid_positions:
            self.ax.axvline(x, color='gray', alpha=0.3, linewidth=0.5)
        for y in grid_positions:
            self.ax.axhline(y, color='gray', alpha=0.3, linewidth=0.5)
        
        # Set ticks at cell boundary positions
        self.ax.set_xticks(grid_positions)
        self.ax.set_yticks(grid_positions)
        
        # Update titles and labels
        sim_time = getattr(self, 'heatmap_metadata', {}).get('sim_time', 'Unknown')
        dimensions = getattr(self, 'heatmap_metadata', {}).get('dimensions', 'Unknown')
        cell_size = getattr(self, 'heatmap_metadata', {}).get('cell_size', 'Unknown')
        
        title = f'Robot Visit Count Heatmap with Food Locations\n'
        title += f'Time: {sim_time}s | Grid: {dimensions} | Cell: {cell_size}m'
        
        if hasattr(self, 'food_metadata') and self.food_metadata:
            food_count = len(self.food_data) if self.food_data is not None else 0
            title += f' | Food: {food_count} items'
        
        self.ax.set_title(title, fontsize=14)
        self.ax.set_xlabel('World X Coordinate (meters)', fontsize=12)
        self.ax.set_ylabel('World Y Coordinate (meters)', fontsize=12)
        
        # Add legend
        self.ax.legend(loc='upper right', bbox_to_anchor=(1, 1))
        
        # Add statistics text
        if self.grid_data is not None:
            max_visits = np.max(self.grid_data)
            total_visits = np.sum(self.grid_data)
            visited_cells = np.count_nonzero(self.grid_data)
            total_cells = self.grid_data.size
            cell_size = getattr(self, 'heatmap_metadata', {}).get('cell_size', 'Unknown')
            
            # Calculate actual cell dimensions from C++ grid system
            arena_width = 8.0  # meters
            nominal_cell_size = 0.75
            num_cells = int(np.ceil(arena_width / nominal_cell_size))  # 11 cells
            actual_cell_size = arena_width / num_cells  # 8/11 ≈ 0.727m
            
            stats_text = f'Grid: {num_cells}x{num_cells} cells\n'
            stats_text += f'Cell size: {actual_cell_size:.3f}m\n'
            stats_text += f'Max visits: {max_visits:.0f}\n'
            stats_text += f'Total visits: {total_visits:.0f}\n'
            stats_text += f'Visited cells: {visited_cells}/{total_cells}\n'
            
            if self.food_data is not None:
                stats_text += f'Food items: {len(self.food_data)}'
            
            self.ax.text(0.02, 0.98, stats_text, transform=self.ax.transAxes,
                       verticalalignment='top', bbox=dict(boxstyle='round', 
                       facecolor='white', alpha=0.8), fontsize=10)
        
        print(f"Updated display - Heatmap: {self.last_heatmap_file}, Food: {self.last_food_file}")
    
    def start_animation(self):
        """Start the live animation"""
        print(f"Starting live heatmap and food viewer...")
        print(f"Looking for heatmap files: {self.heatmap_pattern}")
        print(f"Looking for food files: {self.food_pattern}")
        print(f"Update interval: {self.update_interval/1000:.1f} seconds")
        print("Close the window to exit.")
        
        # Initial display
        if self.find_latest_csv(self.heatmap_pattern) is None and self.find_latest_csv(self.food_pattern) is None:
            self.ax.text(0.5, 0.5, 'Waiting for CSV files...', 
                        transform=self.ax.transAxes, ha='center', va='center',
                        fontsize=14, color='red')
        
        # Create animation
        ani = animation.FuncAnimation(self.fig, self.update_display, 
                                    interval=self.update_interval, 
                                    blit=False, cache_frame_data=False)
        
        # Show the plot
        plt.tight_layout()
        plt.show()
        
        return ani

def main():
    parser = argparse.ArgumentParser(description='Live Heatmap and Food Viewer for CPFA Grid Data')
    parser.add_argument('--heatmap-pattern', default='heatmap_data/grid_heatmap_*.csv',
                       help='Heatmap CSV file pattern to monitor (default: heatmap_data/grid_heatmap_*.csv)')
    parser.add_argument('--food-pattern', default='food_data/food_locations_*.csv',
                       help='Food CSV file pattern to monitor (default: food_data/food_locations_*.csv)')
    parser.add_argument('--interval', type=int, default=2000,
                       help='Update interval in milliseconds (default: 2000)')
    
    args = parser.parse_args()
    
    try:
        viewer = LiveHeatmapFoodViewer(heatmap_pattern=args.heatmap_pattern,
                                     food_pattern=args.food_pattern,
                                     update_interval=args.interval)
        ani = viewer.start_animation()
        
    except KeyboardInterrupt:
        print("\nViewer stopped by user.")
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()